name: ci
on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        container_image:
          ["archlinux", "ubuntu20"]
        git_tag:
          [
            "v2022.02.14.00",
            "v2022.02.07.00",
            "v2022.01.03.00",
            "v2021.11.01.00",
            "v2021.10.04.00",
          ]

    steps:
      - uses: actions/checkout@v2

      - name: git clone folly
        run: |
          git clone https://github.com/facebook/folly
          cd folly
          git checkout tags/${{ matrix.git_tag }}

      - name: docker build
        run: |
          cd ci/containers/${{ matrix.container_image }}
          bash prepare.sh
          docker build -t ${{ matrix.container_image }} .
