name: ci
on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    container: debian:11

    steps:
      - uses: actions/checkout@v2
      - name: system bootstrap
        run: |
          bash ci/deb_install.sh

      - name: git clone folly
        run: |
          git clone https://github.com/facebook/folly

      - name: compile
        shell: bash
        run: |
          cd folly 
          python3 ./build/fbcode_builder/getdeps.py build

      - name: test
        shell: bash
        run: |
          cd folly 
          python3 ./build/fbcode_builder/getdeps.py test || true
