name: ci
on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        container_image:
          [
            "ubuntu:18.04",
            "debian:10",
            "ubuntu:20.04",
            "debian:11",
            "debian:sid",
          ]
        git_tag: ["v2021.05.03.00"]
    container:
      image: ${{ matrix.container_image }}
    env:
      GET_DEPS_PY: folly/build/fbcode_builder/getdeps.py
    steps:
      - uses: actions/checkout@v2
      - name: system bootstrap
        run: |
          bash ci/deb_install.sh

      - name: Setup brew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"' >> /github/home/.profile
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"

      - name: install mold
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install mold
          mold --version

      - name: git clone folly
        run: |
          git clone https://github.com/facebook/folly
          cd folly
          git checkout tags/${{ matrix.git_tag }}

      - name: Fetch 
        run:  | 
          export PATH=/home/linuxbrew/.linuxbrew/bin:${PATH}
          export GET_DEPS=${{ env.GET_DEPS_PY }}
          mold -run ${GET_DEPS} fetch --no-tests boost
          mold -run ${GET_DEPS} fetch --no-tests ninja
          mold -run ${GET_DEPS} fetch --no-tests cmake
          mold -run ${GET_DEPS} fetch --no-tests double-conversion
          mold -run ${GET_DEPS} fetch --no-tests fmt
          mold -run ${GET_DEPS} fetch --no-tests gflags
          mold -run ${GET_DEPS} fetch --no-tests glog
          mold -run ${GET_DEPS} fetch --no-tests googletest
          mold -run ${GET_DEPS} fetch --no-tests libevent
          mold -run ${GET_DEPS} fetch --no-tests lz4
          mold -run ${GET_DEPS} fetch --no-tests snappy
          mold -run ${GET_DEPS} fetch --no-tests zstd
          mold -run ${GET_DEPS} fetch --no-tests autoconf
          mold -run ${GET_DEPS} fetch --no-tests automake
          mold -run ${GET_DEPS} fetch --no-tests libtool
          mold -run ${GET_DEPS} fetch --no-tests libsodium
      - name: Build boost
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests boost
      - name: Build ninja
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests ninja
      - name: Build cmake
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests cmake
      - name: Build double-conversion
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests double-conversion
      - name: Build fmt
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests fmt
      - name: Build gflags
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests gflags
      - name: Build glog
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests glog
      - name: Build googletest
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests googletest
      - name: Build libevent
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests libevent
      - name: Build lz4
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests lz4
      - name: Build snappy
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests snappy
      - name: Build zstd
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests zstd
      - name: Build autoconf
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests autoconf
      - name: Build automake
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests automake
      - name: Build libtool
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests libtool
      - name: Build libsodium
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --no-tests libsodium
      - name: Build folly
        run: /home/linuxbrew/.linuxbrew/bin/mold -run python3 ${{ env.GET_DEPS_PY }} build --src-dir=folly folly  --project-install-prefix folly:/usr/local
      - name: Copy artifacts
        run: python3 ${{ env.GET_DEPS_PY }} fixup-dyn-deps --strip --src-dir=folly folly _artifacts/linux  --project-install-prefix folly:/usr/local --final-install-prefix /usr/local
      - uses: actions/upload-artifact@v2
        with:
          name: folly
          path: folly/_artifacts
      - name: Test folly
        run: python3 ${{ env.GET_DEPS_PY }} test --src-dir=folly folly  --project-install-prefix folly:/usr/local
