name: ci
on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        container_image:
          ["ubuntu:18.04", "debian:10", "ubuntu:20.04", "debian:11"]
        git_tag:
          [
            "v2022.01.31.00",
            "v2021.05.03.00",
          ]
    container:
      image: ${{ matrix.container_image }}
    env:
      GET_DEPS_PY: folly/build/fbcode_builder/getdeps.py
    steps:
      - uses: actions/checkout@v2
      - name: system bootstrap
        run: |
          bash ci/deb_install.sh

      - name: git clone folly
        run: |
          git clone https://github.com/facebook/folly
          cd folly
          git checkout tags/${{ matrix.git_tag }}

      - name: Fetch boost
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests boost
      - name: Fetch ninja
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests ninja
      - name: Fetch cmake
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests cmake
      - name: Fetch double-conversion
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests double-conversion
      - name: Fetch fmt
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests fmt
      - name: Fetch gflags
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests gflags
      - name: Fetch glog
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests glog
      - name: Fetch googletest
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests googletest
      - name: Fetch libevent
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests libevent
      - name: Fetch lz4
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests lz4
      - name: Fetch snappy
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests snappy
      - name: Fetch zstd
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests zstd
      - name: Fetch autoconf
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests autoconf
      - name: Fetch automake
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests automake
      - name: Fetch libtool
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests libtool
      - name: Fetch libsodium
        run: python3 ${{ env.GET_DEPS_PY }} fetch --no-tests libsodium
      - name: Build boost
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests boost
      - name: Build ninja
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests ninja
      - name: Build cmake
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests cmake
      - name: Build double-conversion
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests double-conversion
      - name: Build fmt
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests fmt
      - name: Build gflags
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests gflags
      - name: Build glog
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests glog
      - name: Build googletest
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests googletest
      - name: Build libevent
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests libevent
      - name: Build lz4
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests lz4
      - name: Build snappy
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests snappy
      - name: Build zstd
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests zstd
      - name: Build autoconf
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests autoconf
      - name: Build automake
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests automake
      - name: Build libtool
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests libtool
      - name: Build libsodium
        run: python3 ${{ env.GET_DEPS_PY }} build --no-tests libsodium
      - name: Build folly
        run: python3 ${{ env.GET_DEPS_PY }} build --src-dir=folly folly  --project-install-prefix folly:/usr/local
      - name: Copy artifacts
        run: python3 ${{ env.GET_DEPS_PY }} fixup-dyn-deps --strip --src-dir=folly folly _artifacts/linux  --project-install-prefix folly:/usr/local --final-install-prefix /usr/local
      - uses: actions/upload-artifact@v2
        with:
          name: folly
          path: _artifacts
      - name: Test folly
        run: python3 ${{ env.GET_DEPS_PY }} test --src-dir=folly folly  --project-install-prefix folly:/usr/local
