name: ci

on: push

env:
  DEBIAN_FRONTEND: noninteractive

jobs:
  run_system_deps:
    runs-on: ubuntu-20.04
    container: ubuntu:20.04

    steps:
      - uses: actions/checkout@v2

      - name: system bootstrap
        run: |
          bash ci/deb_install.sh

      - name: git clone folly
        run: |
          git clone https://github.com/facebook/folly

      - name: compile
        shell: bash
        run: |
          cd folly 
          python3 ./build/fbcode_builder/getdeps.py install-system-deps --recursive
          python3 ./build/fbcode_builder/getdeps.py --allow-system-packages build

      - name: test
        shell: bash
        run: |
          cd folly 
          python3 ./build/fbcode_builder/getdeps.py --allow-system-packages test || true

  run_no_system_deps:
    runs-on: ubuntu-20.04
    container: ubuntu:20.04

    steps:
      - uses: actions/checkout@v2

      - name: system bootstrap
        run: |
          bash ci/deb_install.sh

      - name: git clone folly
        run: |
          git clone https://github.com/facebook/folly

      - name: compile
        shell: bash
        run: |
          cd folly 
          python3 ./build/fbcode_builder/getdeps.py --allow-system-packages build
          ls /tmp/

      - name: test
        shell: bash
        run: |
          cd folly 
          python3 ./build/fbcode_builder/getdeps.py --allow-system-packages test || true
          ls /tmp/
  centos7:
    runs-on: ubuntu-20.04
    container: centos:7

    steps:
      - uses: actions/checkout@v2

      - name: system bootstrap
        run: |
          yum groupinstall -y "Development tools"
          yum install -y git gcc gcc-c++ make automake autoconf \
            libtool wget python3 python3-devel \
            openssl-devel \
            dnf
          dnf install -y centos-release-scl
          dnf install -y devtoolset-10*

      - name: compile
        shell: bash
        run: |
          source scl_source enable devtoolset-10
          git clone https://github.com/facebook/folly
          cd folly 
          python3 ./build/fbcode_builder/getdeps.py --allow-system-packages build
          ls /tmp/

      - name: test
        shell: bash
        run: |
          source scl_source enable devtoolset-10
          cd folly 
          python3 ./build/fbcode_builder/getdeps.py --allow-system-packages test || true
          ls /tmp/